@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Sep 29 23:10:40 +0200 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Minor_SM_tb_behav -key {Behavioral:sim_1:Functional:Minor_SM_tb} -tclbatch Minor_SM_tb.tcl -view C:/Users/admin/Desktop/Hardware-Serpent-Cyphering/Hardware_serpent_cyphering/MinorSM_with_States.wcfg -log simulate.log"
call xsim  Minor_SM_tb_behav -key {Behavioral:sim_1:Functional:Minor_SM_tb} -tclbatch Minor_SM_tb.tcl -view C:/Users/admin/Desktop/Hardware-Serpent-Cyphering/Hardware_serpent_cyphering/MinorSM_with_States.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
